search-news: true
search-with-filters: false
dark-theme: false

about-disable: false
news-disable: false
service-disable: true
portfolio-disable: true

vk-widget-supports: true
vk-widgets:
  community_messages: true
  groups: true
